services:
  backend:
    build:
      context: ./backend
      dockerfile: DockerFile
    container_name: backend
    ports:
      - "${BACKEND_PORT}:5000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - NODE_ENV=development
    volumes:
      - ./backend:/app
      - /app/node_modules
      - /app/.pnpm-store
    command: pnpm run start:dev
    depends_on:
      - db
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: DockerFile
    container_name: frontend
    ports:
      - "${FRONTEND_PORT}:3000"
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.pnpm-store
    command: pnpm run dev
    depends_on:
      - backend
